# BE2 - Algorithmes efficaces via la Programmation Linéaire

Préparé par Anass El Houd - Cours de Recherche Opérationnelle.
BE de Monsieur Nicolas BOUSQUET. 

Le rapport est en Pj de ce notebook.

In [3]:
import pandas as pd
import numpy as np
import math

#### Question 10.a.

In [4]:
def adj_To_Inc(adj):
  n=np.shape(adj)
  edge=0
  inc=np.zeros((n[0]**2,n[0])) 

  for i in range(0,n[0]):
    for j in range(i):
       if (adj[i][j]):
         inc[edge][i]=1
         inc[edge][j]=1
         edge=edge+1
            
  inc=inc[:edge][:]

  return inc

In [5]:
#La matrice d'adjacence d'un cycle de 4 sommets
adj1=[[0,1,0,1],
      [1,0,1,0],
      [0,1,0,1],
      [1,0,1,0]]

adj_To_Inc(adj1)

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 1.]])

In [6]:
#La matrice d'adjacence d'un chemin à 4 sommets
adj2=[[0,1,1,0],
      [1,0,0,0],
      [1,0,0,1],
      [0,0,1,0]]

adj_To_Inc(adj2)

array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 1.]])

In [7]:
#La matrice d'adjacence d'un clique à 4 sommets
adj3=[[0,1,1,1],
      [1,0,1,1],
      [1,1,0,1],
      [1,1,1,0]]

adj_To_Inc(adj3)

array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 1.]])

#### Question 10.b.

In [47]:
def inc_to_adj(inc):
  m=np.shape(inc)
  adj=np.zeros((m[1],m[1]))
  count=0
  k=0

  for i in range(m[0]):

    for j in range(m[1]):
      if (inc[i][j]==1 and count==0):
        count = 1
        k=j

      elif (inc[i][j]==1 and count==1):
        count=0
        adj[k,j]=1
        adj[j,k]=1
        k=0

  return adj

In [48]:
#La matrice d'incidence d'un cycle de 4 sommets
incid1=[[1,1,0,0],
        [0,1,1,0],
        [0,0,1,1],
        [1,0,0,1]]

inc_to_adj(incid1)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [49]:
#La matrice d'incidence d'un chemin à 4 sommets
incid2=[[1, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 0, 1, 1]]

inc_to_adj(incid2)

array([[0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [51]:
#La matrice d'incidence d'un clique à 4 sommets
incid3=[[1, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1],
        [0, 1, 0, 1],
        [0, 0, 1, 1]]

inc_to_adj(incid3)

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

En effet, on remarque qu'il y a une équivalence entre les deux méthodes qu'on vient d'implémenter. Les réponses sont correctes.

#### Question 11.a.

Écrire une fonction qui renvoie un couplage maximal fractionnaire étant donné un graphe G en entrée ainsi que sa valeur

In [27]:
from scipy.optimize import linprog

def couplage_max(inc):
  if inc==[]:
    C=[]
    N=0

  else:
    m=np.shape(inc)
    c=-np.ones(m[0])
    A=np.transpose(inc)
    b=np.ones(m[1])
    lb=np.zeros(m[0])
    ub=np.ones(m[0])

    res = linprog(c, A_ub=A, b_ub=b, bounds=[0,1])

    return res

In [28]:
#cycle de 4 sommets
couplage_max(incid1)

     con: array([], dtype=float64)
     fun: -2.0000000161570175
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([-8.07860978e-09, -8.07857736e-09, -8.07840816e-09, -8.07844036e-09])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5])

In [29]:
#chemin de 4 sommets
couplage_max(incid2)

     con: array([], dtype=float64)
     fun: -2.000000000006429
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([-3.21476179e-12,  2.37691350e-01, -3.21431770e-12])
  status: 0
 success: True
       x: array([0.38115433, 0.61884567, 0.38115433, 0.61884567])

In [14]:
#clique de 4 sommets
couplage_max(incid3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: OptimizeWarning: Solving system with option 'cholesky':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'cholesky' to False.
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: OptimizeWarning: Solving system with option 'sym_pos':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'sym_pos' to False.
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/scipy/optimize/_linprog_ip.py:110: LinAlgWarning: Ill-conditioned matrix (rcond=4.40125e-18): result may not be accurate.
  return sp.linalg.solve(M, r, sym_pos=sym_pos)


     con: array([], dtype=float64)
     fun: -2.000000000004153
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([-2.50133247e-12, -1.85806925e-12, -1.65156777e-12, -2.29483099e-12,
       -1.86828331e-12, -2.28461694e-12])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5])

#### Question 11.b.

Qu’est ce qui est renvoyé pour la relaxation fractionnaire du
problème de couplage maximum?

In [30]:
def relax_frac(inc):
  if inc==[]:
    C=[]
    N=0

  else:
    m=np.shape(inc)
    c=-np.ones(m[0])
    A=np.transpose(inc)
    b=np.ones(m[1])

    res = linprog(c, A_ub=A, b_ub=b, bounds=[0,None])

    return res

In [16]:
#cycle de 4 sommets
relax_frac(incid1)

     con: array([], dtype=float64)
     fun: -2.0000000001615756
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([-8.07951483e-11, -8.08049183e-11, -8.07807155e-11, -8.07709455e-11])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5])

In [17]:
#chemin de 4 sommets
relax_frac(incid2)

     con: array([], dtype=float64)
     fun: -2.0000000121175203
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([-6.05875994e-09,  3.33333327e-01, -6.05876016e-09])
  status: 0
 success: True
       x: array([0.33333334, 0.66666667, 0.33333334, 0.66666667])

In [18]:
#clique de 4 sommets
relax_frac(incid3)

     con: array([], dtype=float64)
     fun: -2.0000000010379684
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([-5.18984411e-10, -5.18983967e-10, -5.18983967e-10, -5.18984411e-10,
       -5.18984855e-10, -5.18983523e-10])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5])

#### Question 12.

Quelles sont les solutions du problème pour la relaxation fractionnaire de “vertex cover minimal” et “couplage maximal” pour un cycle à 5
sommets.

In [31]:
def vertexcover_minimal(inc):
  if inc==[]:
    C=[]
    N=0

  else:
    m=np.shape(inc)
    c=np.ones(m[1]);
    A=np.negative(inc);
    b=-np.ones(m[0]);

    res = linprog(c, A_ub=A, b_ub=b, bounds=[0,1])

  return res

In [20]:
#La matrice d'incidence d'un cycle de 5 sommets
incid5=[[1,1,0,0,0],
        [0,1,1,0,0],
        [0,0,1,1,0],
        [0,0,0,1,1],
        [1,0,0,0,1]]

couplage_max(incid5) 

     con: array([], dtype=float64)
     fun: -2.500000016713985
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([-6.68554234e-09, -6.68561184e-09, -6.68566136e-09, -6.68558631e-09,
       -6.68556810e-09])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5, 0.5])

In [21]:
vertexcover_minimal(incid5)

     con: array([], dtype=float64)
     fun: 2.5000000003080562
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([1.23222543e-10, 1.23222765e-10, 1.23222543e-10, 1.23222321e-10,
       1.23222321e-10])
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5, 0.5])

#### Question 13.a.

Écrire une fonction qui prend comme paramètre n et p et renvoie un graphe de G(n, p). Autrement dit, implémentez une fonction qui génère un graphe de taille n où l’existence de chaque arête est tirée avec probabilité p

In [34]:
import random
def graphNP(n,p):

  adj=np.zeros((n,n))

  for i in range(0,n):
      for j in range(i+1,n):
        if random.random()<p:
          adj[j,i]=1
          adj[i,j]=1

  G=adj_To_Inc(adj)

  return G

In [33]:
graphNP(30,1/2)

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 1.]])

#### Question 13.b.

In [59]:
def edge_calculate(inc):

  return np.shape(inc)[0]

#exemple de cycle (4 arêtes)
edge_calculate(incid1)

4

#### Question 13.c.

Donnez la valeur moyenne de la solution optimale de la relaxation fractionnaire couplage maximal (sur 10 tirages) pour G(30, 1/30), G(30, 1/10)
et G(30, 1/2).

In [37]:
funlist = []
i=0
while i < 10:
  funlist.append(vertexcover_minimal(graphNP(30,1/2)).fun)
  i=i+1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: OptimizeWarning: Solving system with option 'cholesky':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'cholesky' to False.
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: OptimizeWarning: Solving system with option 'sym_pos':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'sym_pos' to False.
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/scipy/optimize/_linprog_ip.py:110: LinAlgWarning: Ill-conditioned matrix (rcond=1.55617e-19): result may not be accurate.
  return sp.linalg.solve(M, r

In [38]:
print("La valeur moyenne de la solution optimale = ", np.mean(funlist))

La valeur moyenne de la solution optimale =  15.00000000010204


## Optionnel (**)

#### Question 14.a.

In [39]:
from math import ceil, floor

def solveurGlob(inc):
  sol=abs(relax_frac(inc).fun)

  if isinstance(sol, int):
    return sol

  else:
    m=np.shape(inc)
    c=-np.ones(m[0])
    A=np.transpose(inc)
    b=np.ones(m[1])
    res1 = linprog(c, A_ub=A, b_ub=b, bounds=[0,floor(sol)])
    res2 = linprog(c, A_ub=A, b_ub=b, bounds=[ceil(sol),None])

    return sol, abs(res1.fun), abs(res2.fun)

In [40]:
solveurGlob(graphNP(30,1/30))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: OptimizeWarning: Solving system with option 'cholesky':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'cholesky' to False.
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: OptimizeWarning: Solving system with option 'sym_pos':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'sym_pos' to False.
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: OptimizeWarning: Solving system with option 'sym_pos':False failed. This may happen occasionally, especially as the solution 

(8.50000000000271, 8.49999999931708, 0.0)